# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15139db38e5ec3a47feb059e8c91d4bb871320d96148e525ce5450a3bf2a169ef700dfe31bc065817a934052978a081cfbf4e1debeda2bea36ec4be45650fe79

test:
  secret_key_base: f3f992e02f8e6fe827771f5e815fc48d70ff3194529eff8ed0661179994814eef86a26fad1e12a689e0663ac55e261611c0b3ff1a130e9da79d1dfb18f3a6246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
